apiVersion: v1
kind: Secret
metadata:
  name: ldap-secrets
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: ldap
    app.kubernetes.io/part-of: bi-platform
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: "adminpassword"
  LDAP_CONFIG_PASSWORD: "configpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secrets
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: keycloak-db
    app.kubernetes.io/part-of: bi-platform
type: Opaque
stringData:
  POSTGRES_DB: "keycloak"
  POSTGRES_USER: "keycloak"
  POSTGRES_PASSWORD: "keycloakpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: bi-platform
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_DB_PASSWORD: "keycloakpassword"
  SUPERSET_CLIENT_SECRET: "superset-client-secret-12345"
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: superset
    app.kubernetes.io/part-of: bi-platform
type: Opaque
stringData:
  SUPERSET_SECRET_KEY: "superset-secret-key-change-in-production-12345"
  POSTGRES_DB: "superset"
  POSTGRES_USER: "superset"
  POSTGRES_PASSWORD: "supersetpassword"
  SUPERSET_ADMIN_PASSWORD: "adminpassword"
  SUPERSET_OIDC_CLIENT_SECRET: "superset-client-secret-12345"
