apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data-pvc
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: ldap
    app.kubernetes.io/part-of: bi-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-config-pvc
  namespace: superset-bi
  labels:
    app.kubernetes.io/component: ldap
    app.kubernetes.io/part-of: bi-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

