apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: superset-bi
  labels:
    app: openldap
    app.kubernetes.io/component: ldap
    app.kubernetes.io/part-of: bi-platform
spec:
  type: ClusterIP
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 636
      protocol: TCP

