apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: superset-bi
  labels:
    app: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: bi-platform
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

