apiVersion: v1
kind: Service
metadata:
  name: superset-redis
  namespace: superset-bi
  labels:
    app: superset-redis
    app.kubernetes.io/component: superset-redis
    app.kubernetes.io/part-of: bi-platform
spec:
  type: ClusterIP
  selector:
    app: superset-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP

